### ISSUE TITLE
Publish to the Terraform Registry

### ISSUE THREAD

**Issue by alonsodomin** [Lucretius/terraform-provider-drone#5]
So allow the usage of this provider from Terraform Cloud or similar, the provider should be available in the terraform registry

**Comment by Lucretius** [comment]
Good call out, I will try to set aside some time this week to get this on the registry.

**Comment by Lucretius** [comment]
@alonsodomin I've gone and published the provider to the terraform registry https://registry.terraform.io/providers/Lucretius/drone/latest

**Comment by alonsodomin** [comment]
Many thanks, that was faster than I could expect. I’ll test it this week and hope to get rid of the dirty hack we have right now.

**Comment by Lucretius** [comment]
Great, and yes if you have any issues let me know.  I do not use the provider anymore so have not actually tested out using the registry reference.
